# Generated by Django 3.0.6 on 2020-06-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actName', models.CharField(max_length=40, verbose_name='Nombre Actividad')),
                ('actPhoto', models.ImageField(upload_to='activ_image', verbose_name='Imagen Actividad')),
                ('actDesc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('actDate', models.DateField(verbose_name='Fecha Actividad')),
                ('actTimei', models.TimeField(verbose_name='Hora Inicio')),
                ('actTimef', models.TimeField(verbose_name='Hora Fin')),
                ('actDir', models.CharField(max_length=100, verbose_name='Dirección')),
                ('actPers', models.CharField(max_length=60, verbose_name='Encargado')),
                ('actPhono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Celular ')),
                ('actPhono2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Convencional ')),
                ('actMail', models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='Correo Electrónico ')),
                ('actStatus', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Actividades',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='CasaOracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('place', models.CharField(max_length=100, null=True, verbose_name='Lugar de Reunion')),
                ('responsable', models.CharField(max_length=100, null=True, verbose_name='Responsable')),
                ('frecuency', models.CharField(max_length=50, verbose_name='Frecuencia')),
                ('day', models.CharField(max_length=50, verbose_name='Dia')),
                ('initial_time', models.TimeField(verbose_name='Hora inicio')),
                ('final_time', models.TimeField(verbose_name='Hora fin')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Casa Oracion',
                'verbose_name_plural': 'Casa Oraciones',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('event_time', models.TimeField(verbose_name='Hora del Evento')),
                ('primary_street', models.CharField(max_length=100, verbose_name='Calle principal')),
                ('secondary_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle secundaria')),
                ('house_number', models.CharField(max_length=100, verbose_name='Numero Domicilio')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('description', models.TextField(max_length=200)),
                ('image_ev', models.ImageField(blank=True, upload_to='event_image', verbose_name='Imagen')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='FormularioRecursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_person', models.CharField(max_length=100, verbose_name='Nombre de la persona')),
                ('mail_persona', models.EmailField(max_length=30, verbose_name='Correo de la persona')),
                ('section_category', models.CharField(choices=[('Oracion', 'Oracion'), ('Peticion', 'Peticion')], default='Oracion', max_length=100)),
                ('title', models.CharField(max_length=30, verbose_name='Titulo de Oración/Petición')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción de la Oración/Petición')),
                ('status', models.BooleanField(default=False, verbose_name='Estado Publicado/No_Publicado')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=30, verbose_name='Nombre Grupo')),
                ('grouPhoto', models.ImageField(upload_to='group_image', verbose_name='Imagen Grupo')),
                ('groupDir', models.CharField(max_length=100, verbose_name='Direccion')),
                ('groupStatus', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('miemName1', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('miemName2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('miemSurname1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('miemSurname2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('miemOcu', models.CharField(max_length=30, verbose_name='Ocupación')),
                ('miemPho1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Convencional')),
                ('miemPho2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Celular')),
                ('miemCrea', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('miemDesc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minisName', models.CharField(max_length=40, verbose_name='Nombre Ministerio')),
                ('minisDir', models.CharField(max_length=100, verbose_name='Lugar de Reunión')),
                ('minisPers', models.CharField(max_length=80, verbose_name='Responsable')),
                ('minisFrec', models.CharField(max_length=20, verbose_name='Frecuencia')),
                ('minisCola', models.CharField(max_length=20, verbose_name='Colaboradores')),
                ('minisPhoto', models.ImageField(upload_to='minis_image', verbose_name='Imagen Ministerio')),
                ('minisDesc', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('miniStatus', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Ministerios',
                'verbose_name_plural': 'Ministerios',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del PDF')),
                ('pdf', models.FileField(max_length=254, upload_to='Recursos PDF')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
