# Generated by Django 3.0.6 on 2020-05-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado Activo/Desactivado')),
            ],
        ),
    ]
