# Generated by Django 3.0.7 on 2020-06-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casaoracion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado'),
        ),
    ]
