# Generated by Django 3.0.6 on 2020-06-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariorecursos',
            options={},
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='groupStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='minisCola',
            new_name='collaborators',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='minisDesc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='minisDir',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='minisFrec',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='minisPhoto',
            new_name='ministry_image',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='minisName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='minisPers',
            new_name='responsible_person',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='miniStatus',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='grouPhoto',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='groupDir',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='groupName',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='description_pdf',
        ),
        migrations.AddField(
            model_name='groups',
            name='collaborators',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Colaboradores'),
        ),
        migrations.AddField(
            model_name='groups',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='groups',
            name='direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='groups',
            name='finish_hour',
            field=models.TimeField(null=True, verbose_name='Hora Fin'),
        ),
        migrations.AddField(
            model_name='groups',
            name='frequency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_image', verbose_name='Imagen Grupo'),
        ),
        migrations.AddField(
            model_name='groups',
            name='initial_hour',
            field=models.TimeField(null=True, verbose_name='Hora Inicio'),
        ),
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Grupo'),
        ),
        migrations.AddField(
            model_name='groups',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Responsable'),
        ),
    ]
