# Generated by Django 3.0.6 on 2020-06-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200616_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='collaborators',
            field=models.CharField(max_length=20, verbose_name='Colaboradores'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='direction',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='finish_hour',
            field=models.TimeField(verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='frequency',
            field=models.CharField(max_length=20, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_image',
            field=models.ImageField(upload_to='group_image', verbose_name='Imagen Grupo'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='initial_hour',
            field=models.TimeField(verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre Grupo'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='responsible_person',
            field=models.CharField(max_length=80, verbose_name='Responsable'),
        ),
    ]
