# Generated by Django 3.0.6 on 2020-05-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200529_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
