# Generated by Django 3.0.6 on 2020-05-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200529_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autName1', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('autName2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('autSurname1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('autSurname2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('autMail', models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('autStatus', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado'),
        ),
    ]
