# Generated by Django 3.0.6 on 2020-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_evento_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='invited',
            field=models.CharField(default='Ninguno', max_length=100, verbose_name='Invitado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='secondary_street',
            field=models.CharField(default='', max_length=100, verbose_name='Calle secundaria'),
        ),
    ]
