# Generated by Django 3.0.6 on 2020-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_miembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='miemCrea',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
