# Generated by Django 3.0.6 on 2020-05-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200530_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('event_time', models.TimeField(verbose_name='Hora del Evento')),
                ('primary_street', models.CharField(max_length=100, verbose_name='Calle principal')),
                ('secondary_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle secundaria')),
                ('house_number', models.CharField(max_length=100, verbose_name='Numero Domicilio')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('description', models.TextField(max_length=200)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
