# Generated by Django 3.0.6 on 2020-06-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200624_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='category',
            field=models.CharField(choices=[(1, 'Espirituales'), (2, 'Sociales')], max_length=30, verbose_name='Categoria'),
        ),
    ]
