# Generated by Django 3.0.6 on 2020-05-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_image', verbose_name='Imagen'),
        ),
    ]
