# Generated by Django 3.0.6 on 2020-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_evento_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=30, verbose_name='Nombre Grupo')),
                ('grouPhoto', models.ImageField(upload_to='group_image', verbose_name='Imagen Grupo')),
                ('groupDir', models.CharField(max_length=100, verbose_name='Direccion')),
                ('groupStatus', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minisName', models.CharField(max_length=40, verbose_name='Nombre Ministerio')),
                ('minisPhoto', models.ImageField(upload_to='minis_image', verbose_name='Imagen Ministerio')),
                ('minisDir', models.CharField(max_length=100, verbose_name='Direccion')),
                ('miniStatus', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
            ],
            options={
                'verbose_name': 'Ministerios',
                'verbose_name_plural': 'Ministerios',
            },
        ),
    ]
