# Generated by Django 3.0.6 on 2020-05-31 21:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_groups_ministry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('description', models.CharField(max_length=110, verbose_name='Descriopción')),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.URLField(max_length=255)),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
