# Generated by Django 3.0.6 on 2020-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_groups_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='miemIma',
            field=models.ImageField(blank=True, upload_to='member_image', verbose_name='Imagen'),
        ),
    ]
