# Generated by Django 3.0.6 on 2020-06-26 18:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_edificadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firts_name', models.CharField(max_length=255, verbose_name='Nombres de Autor')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos de Autor')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('status', models.BooleanField(default=True, verbose_name='Autor Activo/No Activo')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'AutorPost',
                'verbose_name_plural': 'AutoresPosts',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
                ('status', models.BooleanField(default=True, verbose_name='Categoria Activada/Categoria no Activada')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'CategoriaPost',
                'verbose_name_plural': 'CategoriasPosts',
            },
        ),
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField()),
                ('picture', models.URLField(max_length=255)),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('auth_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.AutorPost')),
                ('category_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.CategoriaPost')),
            ],
            options={
                'verbose_name': 'PostBlog',
                'verbose_name_plural': 'PostsBlog',
            },
        ),
    ]
