# Generated by Django 3.0.6 on 2020-06-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_autorpost_categoriapost_postblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='description_r',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion'),
        ),
    ]
