# Generated by Django 3.0.7 on 2020-06-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20200531_1559'),
        ('Post', '0010_auto_20200531_1757'),
    ]

    operations = [
    ]
