# Generated by Django 3.0.6 on 2020-06-26 19:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_recurso_description_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='description_r',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
