# Generated by Django 3.0.6 on 2020-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_merge_20200605_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='minisPers',
            field=models.CharField(max_length=80, null=True, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='minisDir',
            field=models.CharField(max_length=100, verbose_name='Lugar de Reunión'),
        ),
    ]
