# Generated by Django 3.0.7 on 2020-06-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_auto_20200626_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariorecursos',
            name='creation_date',
            field=models.DateField(default='2020-06-06', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='member_image',
            field=models.ImageField(upload_to='member_image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='ocupation',
            field=models.CharField(max_length=200, verbose_name='Ocupación'),
        ),
    ]
