# Generated by Django 3.0.6 on 2020-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_auto_20200610_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='minisPers',
            field=models.CharField(max_length=80, verbose_name='Responsable'),
        ),
    ]
