# Generated by Django 3.0.6 on 2020-06-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_auto_20200626_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='date',
        ),
        migrations.AddField(
            model_name='actividades',
            name='day',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], default='---', max_length=10, verbose_name='Día'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='frecuency',
            field=models.CharField(default='---', max_length=40, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='mail',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Correo Electrónico '),
        ),
    ]
