# Generated by Django 3.0.7 on 2020-06-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20200626_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariorecursos',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
