# Generated by Django 3.0.7 on 2020-06-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20200626_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='date',
            field=models.CharField(max_length=20, verbose_name='Dia'),
        ),
    ]
