# Generated by Django 3.0.6 on 2020-06-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20200626_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='day',
            field=models.CharField(choices=[('Todos los días', 'Todos los días'), ('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], default='Todos los días', max_length=20, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='frecuency',
            field=models.CharField(max_length=40, verbose_name='Frecuencia'),
        ),
    ]
