# Generated by Django 3.0.6 on 2020-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20200610_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='minisCola',
            field=models.CharField(max_length=20, null=True, verbose_name='Colaboradores'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='minisFrec',
            field=models.CharField(max_length=20, null=True, verbose_name='Frecuencia'),
        ),
    ]
