# Generated by Django 3.0.6 on 2020-06-27 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_auto_20200626_2126'),
        ('Post', '0015_auto_20200626_1904'),
    ]

    operations = [
    ]
