# Generated by Django 3.0.6 on 2020-06-27 00:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_postblog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
