# Generated by Django 3.0.6 on 2020-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_auto_20200610_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='minisCola',
            field=models.CharField(max_length=20, verbose_name='Colaboradores'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='minisFrec',
            field=models.CharField(max_length=20, verbose_name='Frecuencia'),
        ),
    ]
