# Generated by Django 3.0.6 on 2020-06-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_merge_20200626_2228'),
        ('Post', '0016_auto_20200626_1809'),
    ]

    operations = [
    ]
