# Generated by Django 3.0.6 on 2020-06-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_auto_20200610_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='minisDesc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
    ]
