# Generated by Django 3.0.7 on 2020-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_auto_20200610_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaOracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('place', models.CharField(max_length=100, null=True, verbose_name='Lugar de Reunion')),
                ('responsable', models.CharField(max_length=100, null=True, verbose_name='Responsable')),
                ('frecuency', models.CharField(max_length=50, verbose_name='Frecuencia')),
                ('day', models.CharField(max_length=50, verbose_name='Dia')),
                ('initial_time', models.TimeField(verbose_name='Hora inicio')),
                ('final_time', models.TimeField(verbose_name='Hora fin')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Casa Oracion',
                'verbose_name_plural': 'Casa Oraciones',
            },
        ),
    ]
