# Generated by Django 3.0.7 on 2020-06-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_auto_20200626_2032'),
        ('Post', '0017_merge_20200626_2136'),
    ]

    operations = [
    ]
