# Generated by Django 3.0.7 on 2020-06-10 20:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_casaoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('prayer', ckeditor.fields.RichTextField()),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado Activado/Desactivado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Categoria')),
            ],
            options={
                'verbose_name': 'Oracion',
                'verbose_name_plural': 'Oraciones',
            },
        ),
    ]
