# Generated by Django 3.0.7 on 2020-06-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_merge_20200626_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.TextField(max_length=100, verbose_name='Nombre imagen')),
                ('image', models.ImageField(upload_to='Galery', verbose_name='Imagen')),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
            },
        ),
        migrations.AlterField(
            model_name='casaoracion',
            name='prayer',
            field=models.TextField(max_length=2048, verbose_name='Oracion'),
        ),
    ]
