# Generated by Django 3.0.6 on 2020-06-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_oracion'),
        ('Post', '0019_activities'),
    ]

    operations = [
    ]
