# Generated by Django 3.0.7 on 2020-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0019_auto_20200628_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nombre imagen'),
        ),
    ]
