# Generated by Django 3.0.6 on 2020-07-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0020_auto_20200628_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaActividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre de la imagen')),
                ('image', models.ImageField(upload_to='Galery', verbose_name='Imagen')),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'GaleriaActividad',
                'verbose_name_plural': 'GaleriasActividades',
            },
        ),
    ]
