# Generated by Django 3.0.6 on 2020-07-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0021_galeriaactividades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GaleriaActividades',
            new_name='GaleriaEventos',
        ),
        migrations.AlterModelOptions(
            name='galeriaeventos',
            options={'verbose_name': 'GaleriaEvento', 'verbose_name_plural': 'GaleriaEventos'},
        ),
    ]
