# Generated by Django 3.0.6 on 2020-06-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0021_oraciosypeticiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraciosypeticiones',
            name='select_category',
            field=models.CharField(choices=[('Oración', 'Oración'), ('Petición', 'Petición')], max_length=100),
        ),
    ]
