# Generated by Django 3.0.6 on 2020-06-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0022_auto_20200610_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraciosypeticiones',
            name='select_category',
            field=models.CharField(choices=[('Oracion', 'Oracion'), ('Peticion', 'Peticion')], max_length=100),
        ),
    ]
