# Generated by Django 3.0.6 on 2020-07-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0022_auto_20200714_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre de la imagen')),
                ('image', models.ImageField(upload_to='Galery', verbose_name='Imagen')),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'GaleriaGrupo',
                'verbose_name_plural': 'GaleriaGrupos',
            },
        ),
        migrations.CreateModel(
            name='GaleriaMinisterio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre de la imagen')),
                ('image', models.ImageField(upload_to='Galery', verbose_name='Imagen')),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'GaleriaMinisterio',
                'verbose_name_plural': 'GaleriaMinisterios',
            },
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
