# Generated by Django 3.0.6 on 2020-06-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0023_auto_20200610_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraciosypeticiones',
            name='select_category',
            field=models.IntegerField(choices=[(1, 'Oracion'), (2, 'Peticion')]),
        ),
    ]
