# Generated by Django 3.0.6 on 2020-06-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0024_auto_20200610_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraciosypeticiones',
            name='select_category',
        ),
    ]
