# Generated by Django 3.0.6 on 2020-06-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0027_o_p_section_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_p',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado Publicado/No_Publicado'),
        ),
    ]
