# Generated by Django 3.0.6 on 2020-06-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0028_o_p_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='image',
            new_name='image_ev',
        ),
    ]
