# Generated by Django 3.0.6 on 2020-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0029_auto_20200610_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del PDF')),
                ('pdf', models.FileField(max_length=254, upload_to='Recursos PDF')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
